id: P001692
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN2460
  title: བཙན་པོའི་རྒྱལ་རབས་སྐབས་ཀྱི་དཔོན་རིགས་ཞིབ་འཇུག
  author: ''
  volumes:
    3cd9438881074687ad0e8b2b09ecff35:
      image_group_id: I3CN2463
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
