id: P001692
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2460
  title: བཙན་པོའི་རྒྱལ་རབས་སྐབས་ཀྱི་དཔོན་རིགས་ཞིབ་འཇུག
  author: ''
  volumes:
    3cd9438881074687ad0e8b2b09ecff35:
      image_group_id: I3CN2463
      title: ''
      volume_number: 1
      total_pages: 388
